storage:
  performance:
    optimizer_config:
      indexing_threshold_kb: 20000

service:
  max_request_size_mb: 64

collection:
  vectors:
    size: 1024
    distance: Cosine
  quantization_config:
    scalar:
      type: int8
      always_ram: true
